### ISSUE TITLE
License shenanigans 

### ISSUE THREAD

**Issue by LambdAurora** [Doraadams/Colorfly#8]
Hi,

Why is the license to my name?

It seems strange and unintended.

**Comment by Doraadams** [comment]
Hello, 

Indeed, it was unintended. When I first started making the mod I was doing research on licenses, and just so happened to have ur dynamic lights mod pulled up (had it installed on my main MC profile). Thought the license was a "copy/paste" kinda thing and used yours as a template. Didn't realize it has your name and email. I will CHANGE ASAP, so sorry.

**Comment by Doraadams** [comment]
Fixed and updated. Again, so sorry about the copy/paste thing, was from when I was learning.
